asyncMVC/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace asyncMVC.Models
{
    public class Employee
    {
        public int id { get; set; }
        public string name { get; set; }
        public int salary { get; set; }
    }
}

asyncMVC/Models/EmployeeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace asyncMVC.Models
{
    public class EmployeeModel
    {
        public int id { get; set; }
        public string name { get; set; }
        public int salary { get; set; }
    }
}

asyncMVC/Areas/Mens/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace asyncMVC.Areas.Mens.Controllers
{
    public class HomeController : Controller
    {
        // GET: Mens/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

asyncMVC/Areas/Womens/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace asyncMVC.Areas.Womens.Controllers
{
    public class HomeController : Controller
    {
        // GET: Womens/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

asyncMVC/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace asyncMVC.Controllers
{
    public class EmployeeController : Controller
    {
        EmployeeDBEntities db = new EmployeeDBEntities();
        // GET: Employee
        public ActionResult Index()
        {
            return View(db.Employees.ToList());
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Employee emp) {

            if (ModelState.IsValid) {
                db.Employees.Add(emp);
                db.SaveChanges();
                return RedirectToAction("index");

            }
            return View(emp);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (id > 0) {
                return View(db.Employees.Where(p=> p.EmployeeId == id).SingleOrDefault());
            }

            return View();
        }

        [HttpPost]
        public ActionResult Edit(Employee emp)
        {

            if (ModelState.IsValid)
            {
                db.Employees.Add(emp);
                db.SaveChanges();
                return RedirectToAction("index");

            }
            return View(emp);
        }

        public ActionResult HelperView() {

            return View();
        }
    }
}

asyncMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using asyncMVC.Models;
namespace asyncMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(EmployeeModel emp)
        {
            if (emp.id == 0) {

                emp.id = 101;
                emp.name = "Arpan";
                emp.salary = 180000;
            }

            return View(emp);
        }
        
        public ActionResult Create() {

            return View();
        }
        [HttpPost]
        public ActionResult Create(EmployeeModel emp)
        {
            try
            {
                return RedirectToAction("Index",emp);
            }
            catch
            {

                return View();
            }
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult GetList() {
            var watch = new Stopwatch();
            watch.Start();
            var country = GetCountry();
            var state = GetState();
            var city = GetCity();
            watch.Stop();
            ViewBag.WatchMilliseconds = watch.ElapsedMilliseconds;
            return View();

        }

        public async Task<ActionResult> GetListAsync() {
            //Create a stopwatch for getting excution time  
            var watch = new Stopwatch();
            watch.Start();
            var country = GetCountryAsync();
            var state = GetStateAsync();
            var city = GetCityAsync();
            var content = await country;
            var count = await state;
            var name = await city;
            watch.Stop();
            ViewBag.WatchMilliseconds = watch.ElapsedMilliseconds;
            return View();

        }

        #region-- > GetCountry Methods  for GetList && GetListAsync
        public string GetCountry()
        {
            Thread.Sleep(3000); //Use - when you want to block the current thread.  
            return "India";
        }
        public async Task<string> GetCountryAsync()
        {
            await Task.Delay(3000); //Use - when you want a logical delay without blocking the current thread.  
            return "India";
        }
        #endregion  
        # region-- > GetState Methods for GetList && GetListAsync

        public string GetState()
        {
            Thread.Sleep(5000); //Use - when you want to block the current thread.  
            return "Gujarat";
        }
        public async Task<string> GetStateAsync()
        {
            await Task.Delay(5000); //Use - when you want a logical delay without blocking the current thread.  
            return "Gujarat";
        }
        #endregion
        
        # region-- > GetCity Methods for GetList && GetListAsync
        public string GetCity()
        {
            Thread.Sleep(6000); //Use - when you want to block the current thread.  
            return "Junagadh";
        }
        public async Task<string> GetCityAsync()
        {
            await Task.Delay(6000); //Use - when you want a logical delay without blocking the current thread.  
            return "Junagadh";
        }
        #endregion


    }
}

asyncMVC/Controllers/MyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace asyncMVC.Controllers
{
    public class MyController : Controller
    {
        // GET: My
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult student() {
            string[] arr = { "CS Student", "ME Student", "PH Student", "EC Student", "EE Student" };
            return PartialView("_student", arr);
        }
    }
}

asyncMVC/Areas/Mens/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Men's Index";
}

<h2>Men's Index</h2>

asyncMVC/Areas/Womens/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Women's Index";
}

<h2>Women's Index</h2>

asyncMVC/Areas/Womens/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

asyncMVC/Views/Employee/Create.cshtml
@model asyncMVC.Employee

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfJoining, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfJoining, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfJoining, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoFileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhotoFileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhotoFileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

asyncMVC/Views/Employee/Edit.cshtml
@model asyncMVC.Employee

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EmployeeId)

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfJoining, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfJoining, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfJoining, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoFileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhotoFileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhotoFileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

asyncMVC/Views/Employee/HelperView.cshtml
@{
    ViewBag.Title = "HelperView";
}

<h2>HelperView</h2>

@helper showdetail(string[] items)
{

    <o>
        @foreach (string obj in items)
        {
            <li>@obj </li>

        }

    </o>
}
<h2>Student Detail</h2>
@showdetail(new string[] { "nitin", "amit", "surbah" });

<h2>Cities</h2>
@showdetail(new string[] { "Nida", "ahmedabad", "surat" });

asyncMVC/Views/Employee/Index.cshtml
@model IEnumerable<asyncMVC.Employee>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfJoining)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhotoFileName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Department)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfJoining)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhotoFileName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.EmployeeId }) |
            @Html.ActionLink("Details", "Details", new { id=item.EmployeeId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.EmployeeId })
        </td>
    </tr>
}

</table>

asyncMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

asyncMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

asyncMVC/Views/Home/Create.cshtml
@model asyncMVC.Models.EmployeeModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm())
{
    <table>
        <tr>
            <td>
                ID:
            </td>
            <td>
                @Html.TextBoxFor(p=>p.id)
            </td>
        </tr>
        <tr>
            <td>
                Name:
            </td>
            <td>
                @Html.TextBoxFor(p => p.name)
            </td>
        </tr>
        <tr>
            <td>
                Salary:
            </td>
            <td>
                @Html.TextBoxFor(p => p.salary)
            </td>
        </tr>
        <tr>
            <td></td>
            <td><input id="btnSave" type="submit" value="save" /></td>
        </tr>
    </table>
}

asyncMVC/Views/Home/GetList.cshtml
@{
    ViewBag.Title = "GetList";
}

<h2>GetList</h2>

asyncMVC/Views/Home/GetListAsync.cshtml
@{
    ViewBag.Title = "GetListAsync";
}

<h2>GetListAsync</h2>

asyncMVC/Views/Home/Index.cshtml
@model asyncMVC.Models.EmployeeModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<table>
    <tr>
        <td>ID:</td>
        <td>@Model.id</td>
    </tr>
    <tr>
        <td>Name:</td>
        <td>@Model.name</td>
    </tr>
    <tr>
        <td>Salary:</td>
        <td>@Model.salary</td>
    </tr>

    @Html.ActionLink("Create", "Create", "Home")
</table>

asyncMVC/Views/My/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

asyncMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
       @{ 
           var myView2Part = Html.Partial("_MyView2");
           myView2Part = new MvcHtmlString(myView2Part.ToString() );
       }
        @myView2Part
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @{ Html.RenderPartial("_MyView");}
        @*<h2>Soemthing to seperate</h2>
        @{ Html.RenderAction("Student", "My");}*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

asyncMVC/Views/Shared/_MyView.cshtml
<footer>
    <p>&copy; @DateTime.Now.Year - My ASP.NET Application!!!!</p>
</footer>

asyncMVC/Views/Shared/_MyView2.cshtml
<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("About", "About", "Home")</li>
            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            <li>@Html.ActionLink("Go To Mens Home", "Index", "Home", new { area = "Mens" }, null)</li>
            <li>@Html.ActionLink("Go To Women's Home", "Index", "Home", new { area = "Womens" }, null)</li>
        </ul>
    </div>
</div>

asyncMVC/Views/Shared/_Student.cshtml
<h2>Student Department</h2>
<ul>
    @foreach (var item in Model) {
        <li>@item</li>
    }

</ul>